### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by asbjornenge** [KZen-networks/thresh-sig#1]
Hi there!

Thanks for fantastic work on this 🎉

I would just recommend you add a `LICENSE` file to your repo to make it more clear to developers and contributors what the license for this software is. I see the `package.json` says MIT - which is great! Adding a LICENSE file makes this even more clear to people looking at this repo 👍

You can read more about this [here](https://help.github.com/en/articles/adding-a-license-to-a-repository)

**Comment by oleiba** [comment]
Hi, thank you for the kind words and for the relevant suggestion.
MIT license was misplaced. We updated the license to GPL-3.0, and added the corresponding LICENSE file in [https://github.com/KZen-networks/thresh-sig/commit/e243000b87a11afe5184bc3a9f3e5308fe914b2b](https://github.com/KZen-networks/thresh-sig/commit/e243000b87a11afe5184bc3a9f3e5308fe914b2b).
